# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\tmypackage\"\x18\n\ncocktailId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0c\x63ocktailName\x12\x0c\n\x04name\x18\x01 \x01(\t2I\n\x04\x44\x61ta\x12\x41\n\x0fgetCocktailName\x12\x15.mypackage.cocktailId\x1a\x17.mypackage.cocktailNameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COCKTAILID._serialized_start=25
  _COCKTAILID._serialized_end=49
  _COCKTAILNAME._serialized_start=51
  _COCKTAILNAME._serialized_end=79
  _DATA._serialized_start=81
  _DATA._serialized_end=154
# @@protoc_insertion_point(module_scope)
